# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import test_rc as test_rc
from window2 import Ui_SecondWindow

class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi( self.window)
        self.window.show()
        MainWindow.close()
       
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 423)
        MainWindow.setMinimumSize(QtCore.QSize(608, 423))
        MainWindow.setMaximumSize(QtCore.QSize(608, 423))
        MainWindow.setStyleSheet("QMainWindow > QWidget {background-image: url(:/bgImage/istockphoto-505583215-612x612.jpg);}\n""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.openWindow())
        self.pushButton.setGeometry(QtCore.QRect(160, 320, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(28)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("color: black;\n"
                                    "background-color: white;\n"
                                    "border-style: outset;\n"
                                    "border-radius:15px;\n"
                                    "border-width:4px;\n"
                                    "border-color: black;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, -10, 491, 121))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start Practice"))
        self.label.setText(_translate("MainWindow", "Cricket Coach Live.."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
